@include('afp-data.charts.polio-virus-detection-by-year-chart')
@include('afp-data.charts.polio-emerging-seasons-chart')
@include('afp-data.charts.polio-emerging-months-chart')
@include('afp-data.charts.polio-virus-distribution-by-gender-chart')
@include('afp-data.charts.suspected-polio-virus-cell-culturing-results-chart')
@include('afp-data.charts.polio-cases-by-province-chart')
